"use client";
import { Search } from "lucide-react";
import Link from "next/link";
import { useState } from "react";
import { Card } from "@/components/ui/card";
import { EmptyState } from "@/components/ui/empty-state";
import { Input } from "@/components/ui/input";
import { PageHeader } from "@/components/ui/page-header";
import { ResponsiveContainer } from "@/components/ui/responsive-container";
const topics = [{ category: "Discovery", question: "How do experience filters work?", answer: "Explore sends search, category, location, budget, rating, sorting, and pagination choices to the RouteMuse API, so each result page is filtered consistently." }, { category: "AI Planner", question: "How is an itinerary generated?", answer: "RouteMuse retrieves relevant published experiences, asks a third-party LLM to organize grounded suggestions, validates its structured response, and recalculates linked experience costs in application code." }, { category: "AI Planner", question: "Can I change a generated plan?", answer: "Yes. Open AI Planner, choose a saved plan, and describe a refinement such as reducing cost, walking, or changing an activity." }, { category: "Recommendations", question: "Why am I seeing a recommendation?", answer: "The recommendation page displays match reasons and a transparent base score informed by your preferences and RouteMuse activity." }, { category: "Privacy", question: "What is shared with AI providers?", answer: "Only bounded travel constraints, summarized preference signals, and necessary experience details are sent. Passwords, access tokens, and email addresses are excluded." }, { category: "Account", question: "How do I save or review an experience?", answer: "Sign in, open an experience detail page, and use its favorite or review controls. Reviews can be submitted once per experience." }];
export function HelpPage() { const [query,setQuery] = useState(""); const filtered = topics.filter((topic) => `${topic.category} ${topic.question} ${topic.answer}`.toLowerCase().includes(query.toLowerCase())); return <main className="bg-slate-50 py-12 sm:py-16"><ResponsiveContainer className="grid gap-8"><PageHeader eyebrow="Help center" title="Find a clear answer" description="Browse guidance for discovery, AI planning, recommendations, accounts, and privacy."/><Input label="Search help topics" placeholder="Search planner, recommendations, privacy…" value={query} onChange={(event) => setQuery(event.target.value)}/>{filtered.length ? <div className="grid gap-4 md:grid-cols-2">{filtered.map((topic) => <Card key={topic.question}><span className="text-xs font-bold uppercase tracking-wider text-teal">{topic.category}</span><h2 className="mt-2 font-bold text-navy">{topic.question}</h2><p className="mt-2 text-sm leading-6 text-slate-600">{topic.answer}</p></Card>)}</div> : <EmptyState icon={Search} title="No help topic matched" description="Try a broader phrase, or contact the RouteMuse team for product support." action={<Link href="/contact" className="rounded-xl bg-teal px-4 py-3 text-sm font-semibold text-white">Contact support</Link>}/>}<nav className="flex flex-wrap gap-4 border-t pt-6 text-sm font-semibold text-teal" aria-label="Help links"><Link href="/contact">Contact support</Link><Link href="/privacy">Privacy</Link><Link href="/terms">Terms</Link><Link href="/explore">Explore experiences</Link></nav></ResponsiveContainer></main>; }
