"use client";

import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Bookmark, Compass, RefreshCw, SlidersHorizontal, Sparkles, Star, ThumbsDown, ThumbsUp } from "lucide-react";
import Image from "next/image";
import Link from "next/link";
import { useState } from "react";
import { toast } from "sonner";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { EmptyState } from "@/components/ui/empty-state";
import { Input } from "@/components/ui/input";
import { PageHeader } from "@/components/ui/page-header";
import { ResponsiveContainer } from "@/components/ui/responsive-container";
import { Select } from "@/components/ui/select";
import { Skeleton } from "@/components/ui/skeleton";
import { useAuth } from "@/context/auth-context";
import { currentUserQueryKey } from "@/hooks/use-current-user";
import { api, getApiErrorMessage } from "@/lib/api";
import type { RecommendationFeedback, RecommendationResult } from "@/types/recommendation";

interface Refinement { category: string; destination: string; maximumPrice: string; minimumRating: string; travelStyle: string; request: string }
const emptyRefinement: Refinement = { category: "", destination: "", maximumPrice: "", minimumRating: "", travelStyle: "", request: "" };

export function RecommendationsPage() {
  const { user } = useAuth(); const queryClient = useQueryClient();
  const [showPreferences, setShowPreferences] = useState(false); const [refinement, setRefinement] = useState(emptyRefinement);
  const [preferences, setPreferences] = useState({ categories: user?.travelPreferences.preferredCategories.join(", ") ?? "", locations: user?.travelPreferences.preferredLocations.join(", ") ?? "", budgetMin: user?.travelPreferences.budgetMin?.toString() ?? "", budgetMax: user?.travelPreferences.budgetMax?.toString() ?? "", travelStyle: user?.travelPreferences.travelStyle ?? "" });
  const recommendations = useQuery({ queryKey: ["recommendations"], queryFn: async () => (await api.get<{ data: RecommendationResult }>("/ai/recommendations")).data.data, staleTime: 60_000 });
  const refine = useMutation({ mutationFn: async () => { const body = Object.fromEntries(Object.entries(refinement).filter(([, value]) => value !== "")); return (await api.post<{ data: RecommendationResult }>("/ai/recommendations/refine", body)).data.data; }, onSuccess: (data) => { queryClient.setQueryData(["recommendations"], data); toast.success("Recommendations refined"); } });
  const savePreferences = useMutation({ mutationFn: async () => (await api.put("/users/me/preferences", { preferredCategories: preferences.categories.split(",").map((value) => value.trim()).filter(Boolean), preferredLocations: preferences.locations.split(",").map((value) => value.trim()).filter(Boolean), ...(preferences.budgetMin ? { budgetMin: Number(preferences.budgetMin) } : {}), ...(preferences.budgetMax ? { budgetMax: Number(preferences.budgetMax) } : {}), ...(preferences.travelStyle ? { travelStyle: preferences.travelStyle } : {}) })).data, onSuccess: async () => { await queryClient.invalidateQueries({ queryKey: currentUserQueryKey }); await recommendations.refetch(); setShowPreferences(false); toast.success("Preferences saved"); } });
  const feedback = useMutation({ mutationFn: async ({ id, value }: { id: string; value: RecommendationFeedback }) => api.post(`/ai/recommendations/${id}/feedback`, { value }), onSuccess: (_data, variables) => toast.success(variables.value === "not_interested" ? "We’ll tune down similar matches" : "Feedback saved") });
  const data = recommendations.data;
  return <main className="min-h-screen bg-slate-50 py-10"><ResponsiveContainer className="grid gap-8">
    <div className="flex flex-wrap items-end justify-between gap-4"><PageHeader eyebrow="Curated for you" title="Personalized recommendations" description="Transparent matches shaped by your preferences, saves, ratings, itinerary choices, and feedback."/><div className="flex gap-2"><Button variant="outline" onClick={() => setShowPreferences((value) => !value)}><SlidersHorizontal size={17}/>Preferences</Button><Button onClick={() => void recommendations.refetch()} isLoading={recommendations.isFetching}><RefreshCw size={17}/>Refresh</Button></div></div>
    {(showPreferences || data?.needsOnboarding) && <Card className="grid gap-5 border-teal/30 bg-teal/5"><div><h2 className="text-xl font-bold text-navy">Shape your recommendation profile</h2><p className="mt-1 text-sm text-slate-600">A few explicit preferences give the agent a useful starting point. Separate multiple values with commas.</p></div><div className="grid gap-4 md:grid-cols-2"><Input label="Preferred categories" placeholder="Nature, Food, Culture" value={preferences.categories} onChange={(event) => setPreferences({ ...preferences, categories: event.target.value })}/><Input label="Preferred locations" placeholder="Japan, Bali, Paris" value={preferences.locations} onChange={(event) => setPreferences({ ...preferences, locations: event.target.value })}/><Input type="number" min="0" label="Minimum budget" value={preferences.budgetMin} onChange={(event) => setPreferences({ ...preferences, budgetMin: event.target.value })}/><Input type="number" min="0" label="Maximum budget" value={preferences.budgetMax} onChange={(event) => setPreferences({ ...preferences, budgetMax: event.target.value })}/><Input label="Travel style" placeholder="Relaxed, adventurous, family-friendly" value={preferences.travelStyle} onChange={(event) => setPreferences({ ...preferences, travelStyle: event.target.value })}/></div><div><Button onClick={() => savePreferences.mutate()} isLoading={savePreferences.isPending}>Save preferences</Button>{savePreferences.isError && <p className="mt-2 text-sm text-red-700">{getApiErrorMessage(savePreferences.error)}</p>}</div></Card>}
    <Card><div className="flex items-center gap-2"><Compass className="text-teal"/><h2 className="text-lg font-bold text-navy">Refine this set</h2></div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><Input label="Category" value={refinement.category} onChange={(event) => setRefinement({ ...refinement, category: event.target.value })}/><Input label="Destination" value={refinement.destination} onChange={(event) => setRefinement({ ...refinement, destination: event.target.value })}/><Input type="number" min="0" label="Maximum price" value={refinement.maximumPrice} onChange={(event) => setRefinement({ ...refinement, maximumPrice: event.target.value })}/><Select label="Minimum rating" placeholder="Any rating" options={[{ value: "3", label: "3+ stars" }, { value: "4", label: "4+ stars" }, { value: "4.5", label: "4.5+ stars" }]} value={refinement.minimumRating} onChange={(event) => setRefinement({ ...refinement, minimumRating: event.target.value })}/><Input label="Travel style" value={refinement.travelStyle} onChange={(event) => setRefinement({ ...refinement, travelStyle: event.target.value })}/><Input label="What should change?" placeholder="More quiet outdoor activities" value={refinement.request} onChange={(event) => setRefinement({ ...refinement, request: event.target.value })}/></div><div className="mt-4 flex gap-2"><Button onClick={() => refine.mutate()} isLoading={refine.isPending}>Apply refinements</Button><Button variant="ghost" onClick={() => setRefinement(emptyRefinement)}>Clear</Button></div>{refine.isError && <p className="mt-3 text-sm text-red-700">{getApiErrorMessage(refine.error)}</p>}</Card>
    {recommendations.isLoading ? <div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{Array.from({ length: 6 }, (_, index) => <Skeleton key={index} className="h-[480px]"/>)}</div> : recommendations.isError ? <EmptyState icon={RefreshCw} title="Recommendations could not load" description={getApiErrorMessage(recommendations.error)} action={<Button onClick={() => void recommendations.refetch()}>Try again</Button>}/> : data?.recommendations.length ? <>
      <Card className="bg-navy text-white"><div className="flex gap-3"><Sparkles className="shrink-0 text-amber"/><div><h2 className="text-xl font-bold">Why these experiences?</h2><p className="mt-2 leading-7 text-slate-300">{data.explanation}</p><p className="mt-2 text-xs text-slate-400">AI-assisted ranking based only on non-sensitive travel signals. You control your feedback.</p></div></div></Card>
      <div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{data.recommendations.map((item, index) => <Card key={item.experience._id} className="flex min-h-[510px] flex-col overflow-hidden p-0"><div className="relative aspect-[16/10] bg-slate-200">{item.experience.imageUrls[0] && <Image fill className="object-cover" sizes="(min-width:1280px) 33vw, 50vw" src={item.experience.imageUrls[0]} alt={`${item.experience.title} in ${item.experience.location}`}/>}<Badge className="absolute left-3 top-3 bg-white">#{index + 1} · {item.matchScore}% match</Badge></div><div className="flex flex-1 flex-col p-5"><div className="flex items-center justify-between gap-2"><Badge>{item.experience.category}</Badge><span className="flex items-center gap-1 text-sm font-semibold"><Star className="size-4 fill-amber text-amber"/>{item.experience.ratingAverage.toFixed(1)}</span></div><h3 className="mt-3 text-lg font-bold text-navy">{item.experience.title}</h3><p className="mt-1 text-sm text-slate-500">{item.experience.location}, {item.experience.country} · ${item.experience.price.toLocaleString()}</p><div className="mt-4 rounded-xl bg-slate-50 p-3"><p className="text-sm leading-6 text-slate-700">{item.reason}</p><p className="mt-2 text-xs text-slate-500">Base score {item.baseScore}/100 · {item.scoreFactors.join(" · ")}</p></div><div className="mt-auto grid grid-cols-3 gap-2 pt-5"><button aria-label="Interested" onClick={() => feedback.mutate({ id: item.experience._id, value: "interested" })} className="grid min-h-11 place-items-center rounded-xl border hover:border-teal hover:text-teal"><ThumbsUp size={17}/></button><button aria-label="Not interested" onClick={() => feedback.mutate({ id: item.experience._id, value: "not_interested" })} className="grid min-h-11 place-items-center rounded-xl border hover:border-red-600 hover:text-red-700"><ThumbsDown size={17}/></button><button aria-label="Save preference" onClick={() => feedback.mutate({ id: item.experience._id, value: "saved" })} className="grid min-h-11 place-items-center rounded-xl border hover:border-teal hover:text-teal"><Bookmark size={17}/></button></div><Link onClick={() => feedback.mutate({ id: item.experience._id, value: "opened" })} href={`/experiences/${item.experience.slug}`} className="mt-2 grid min-h-11 place-items-center rounded-xl bg-teal text-sm font-semibold text-white hover:bg-teal/90">View experience</Link></div></Card>)}</div></> : <EmptyState icon={Compass} title={data?.needsOnboarding ? "Tell RouteMuse what you enjoy" : "No matches found"} description={data?.explanation ?? "Add preferences or broaden your refinements to discover suitable experiences."}/>} 
  </ResponsiveContainer></main>;
}
